Fix TransformComponent rotation method call in createPlane
The method is called setRotationEuler(x, y, z) not setRotation([x, y, z]).

Error was:
  TypeError: transform.setRotation is not a function

Fixed by changing:
  transform.setRotation([-Math.PI / 2, 0, 0])

To:
  transform.setRotationEuler(-Math.PI / 2, 0, 0)

The TransformComponent API uses setRotationEuler(x, y, z) which takes three separate number parameters (Euler angles in radians), not an array.